#!/usr/bin/env python3
"""Slices ONE AI-generated combined grid image (3 cols x 4 rows = 12 tiles,
Peak omitted) into individually-named tile files, ready for
Tools/compose_hill_atlas.py to composite and preview.

This is the guide-conditioned path: generate the exact construction seed with
Tools/generate_hill_guide.py, use that guide as the binding geometry reference
for all 12 non-Peak tiles, then validate and slice the painted result here.
Grid reading order (top-left origin):
  columns (left to right): Left, Mid, Right
  rows (top to bottom):    Layer1, Layer2, Layer3, Layer4

See Docs/Art/BeachTileSet.md's "Layered ground-hill autotile" section for
the guide-generation command and reference-guided image prompt this pairs with.

Usage:
    python3 Tools/slice_hill_grid.py <combined_image.png>
    python3 Tools/slice_hill_grid.py <combined_image.png> --material sand --out-dir <dir>

Then check the result:
    python3 Tools/compose_hill_atlas.py --preview
(Peak is allowed to be missing — compose_hill_atlas.py leaves that one cell
blank rather than erroring, exactly so this 12-tile test works standalone.)
"""

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("This script requires Pillow: pip install Pillow", file=sys.stderr)
    sys.exit(1)

COLS = ["left", "mid", "right"]
ROWS = ["L1", "L2", "L3", "L4"]


def default_out_dir(material: str) -> Path:
    return Path("Assets/Sprites/Tiles/VanillaKingdom/Ground") / f"{material.capitalize()}HillSource"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("image", type=Path, help="the combined 3x4 grid image to slice")
    parser.add_argument("--material", default="sand", help="material name (default: sand)")
    parser.add_argument("--out-dir", type=Path, default=None, help="where to write the 12 sliced tiles (default: Generated/<Material>HillSource/)")
    parser.add_argument(
        "--allow-imperfect",
        action="store_true",
        help="allow legacy non-3:4 sources by cropping remainder pixels (never use for production)",
    )
    args = parser.parse_args()

    if not args.image.is_file():
        print(f"error: image not found: {args.image}", file=sys.stderr)
        sys.exit(1)

    out_dir = args.out_dir if args.out_dir is not None else default_out_dir(args.material)
    out_dir.mkdir(parents=True, exist_ok=True)

    src = Image.open(args.image).convert("RGBA")
    w, h = src.size
    cols, rows = len(COLS), len(ROWS)

    cell_w, cell_h = w // cols, h // rows
    exact = w % cols == 0 and h % rows == 0 and cell_w == cell_h
    if not exact and not args.allow_imperfect:
        print(
            f"error: {w}x{h} is not an exact {cols}:{rows} sheet of square cells "
            f"({w}/{cols}={w/cols:.2f}, {h}/{rows}={h/rows:.2f}). Refusing to crop or "
            "stretch a production source. Regenerate from Tools/generate_hill_guide.py, "
            "or pass --allow-imperfect only for a disposable legacy inspection.",
            file=sys.stderr,
        )
        sys.exit(1)
    if not exact:
        print(
            f"warning: allowing imperfect {w}x{h} source; output cells are "
            f"{cell_w}x{cell_h} and remainder pixels are cropped.",
            file=sys.stderr,
        )

    written = []
    for r, layer in enumerate(ROWS):
        for c, pos in enumerate(COLS):
            box = (c * cell_w, r * cell_h, (c + 1) * cell_w, (r + 1) * cell_h)
            cell = src.crop(box)
            filename = f"terrain_{args.material}_hill_{layer}_{pos}.png"
            path = out_dir / filename
            cell.save(path)
            written.append(path)

    print(f"Sliced {args.image} ({w}x{h}) into {len(written)} tiles ({cell_w}x{cell_h} each) under {out_dir}/")
    print("Peak was NOT generated by this pass — that's expected; compose_hill_atlas.py leaves it blank.")
    print(f"Next: python3 Tools/compose_hill_atlas.py --material {args.material} --preview")


if __name__ == "__main__":
    main()
